// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Bridge__AlertController from "./bridge/alert_controller"
application.register("bridge--alert", Bridge__AlertController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
